### ISSUE TITLE
Error: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by Agrimonia** [ExFly/manageme#1]
回来重新理了一遍代码，配了 gql loader，勉强能跑起来。但是还有很多工作没有做。  
Playground 能用但是跑起前端还是上次的问题：   
![image](https://user-images.githubusercontent.com/20028602/43788455-07345108-9aa0-11e8-9df1-af85a88f1dff.png)
不太懂...后端是已经配置好 CORS 了吗？

**Comment by ExFly** [comment]
修复方案已经推到fix-#1分支，看一下是否解决您的问题
